version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestFLOW_06_08Project
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestFLOW_06_08Project
  gitUsername: PoojaAnandGit
  gitBranch: main
